version: "3.3"

services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: cccev
    ports:
      - "27018:27017"
    volumes:
      - cccev_mongodb:/data/db/

volumes:
  cccev_mongodb: