server:
  port: 8083

springdoc:
  api-docs:
    path: /api-docs

spring:
  codec:
    max-in-memory-size: 10MB
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/cccev?authSource=admin
      auto-index-creation: true