version: '3.8'

services:
  fs-gateway:
    container_name: fs-cccev
    image: ghcr.io/komune-io/fs-gateway:${VERSION_CONNECT}
    environment:
      - fs_s3_internal-url=http://minio:9000
      - fs_s3_external-url=http://localhost:9000
      - fs_s3_bucket=cccev
      - fs_s3_username=minio
      - fs_s3_password=minio123
    ports:
      - "8090:8090"

networks:
  net:
    name: ${DOCKER_NETWORK}
    external: true